# This is the definitive workflow using robust, pattern-based file splitting.
# It is tailored specifically for your op.js file structure.
name: Generate Final Worker Script (Robust Version)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'op.js'

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install JavaScript Obfuscator
        run: npm install javascript-obfuscator

      # Core Step: Split using content patterns, obfuscate logic, then combine.
      - name: Split, Obfuscate, and Combine
        run: |
          # --- 1. Split File using `sed` (Robust Method) ---
          # This method is not dependent on line numbers.
          
          # Extract the header: everything BEFORE the line with "export default {"
          # The sed command prints lines until it finds the pattern, then quits.
          # We use `sed '$d'` to remove the matching line itself from the header.
          sed '/^export default {/q' op.js | sed '$d' > op.config.js

          # Extract the logic: everything FROM the line with "export default {" to the end.
          # The sed command finds the pattern and prints from that line to the end of the file.
          sed -n '/^export default {/,$p' op.js > op.logic.js
          
          echo "File split successfully based on 'export default {' pattern."

          # --- 2. Obfuscate the Logic Part ---
          cat > obfuscate-logic.js <<'EOF'
          const fs = require("fs");
          const path = require("path");
          const JavaScriptObfuscator = require("javascript-obfuscator");

          const sourceFile = "op.logic.js"; // Input: logic part only
          const outputDir = "dist";
          const outputFile = path.join(outputDir, "opp.logic.obfuscated.js"); // Output: obfuscated logic

          if (!fs.existsSync(sourceFile)) { process.exit(1); }
          if (!fs.existsSync(outputDir)) { fs.mkdirSync(outputDir); }
          const originalCode = fs.readFileSync(sourceFile, "utf8");

          // Obfuscation options
          const obfuscationOptions = {
              esModule: true,
              compact: true,
              controlFlowFlattening: true,
              deadCodeInjection: true,
              stringArray: true,
              renameGlobals: true,
          };

          const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();
          fs.writeFileSync(outputFile, obfuscatedCode, "utf8");
          console.log(`Obfuscated logic saved to: ${outputFile}`);
          EOF
          node obfuscate-logic.js

          # --- 3. Combine Files ---
          # Add a newline for better formatting after the config
          echo "" >> op.config.js
          # Combine the clean config header and the obfuscated logic into the final file
          cat op.config.js dist/opp.logic.obfuscated.js > dist/opp.js
          echo "Final opp.js file created successfully."

      - name: Commit and push the final file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add dist/opp.js
          
          if git diff --staged --quiet; then
            echo "No changes to commit, dist/opp.js is already up-to-date."
          else
            git commit -m "build: Generate final obfuscated worker script"
            git push
          fi
