name: Split-Obfuscate-Combine Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'op.js'

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install JavaScript Obfuscator
        run: npm install javascript-obfuscator

      # 這是最關鍵的核心步驟
      - name: Split, Obfuscate, and Combine
        run: |
          # --- 1. 分割文件 ---
          # 檢查 op.js 是否存在且行數大於 2
          if [ ! -f op.js ] || [ $(wc -l < op.js) -le 2 ]; then
            echo "错误：op.js 文件不存在或内容不完整。"
            exit 1
          fi

          # 將 op.js 的前兩行 (配置) 保存到 op.config.js
          head -n 2 op.js > op.config.js
          # 將 op.js 從第三行開始的所有內容 (邏輯) 保存到 op.logic.js
          tail -n +3 op.js > op.logic.js
          echo "File split into config and logic parts."

          # --- 2. 混淆邏輯部分 ---
          # 創建一個只混淆 op.logic.js 的臨時腳本
          cat > obfuscate-logic.js <<'EOF'
          const fs = require("fs");
          const path = require("path");
          const JavaScriptObfuscator = require("javascript-obfuscator");

          const sourceFile = "op.logic.js"; // 輸入：只混淆邏輯部分
          const outputDir = "dist";
          const outputFile = path.join(outputDir, "opp.logic.obfuscated.js"); // 輸出：混淆後的邏輯

          if (!fs.existsSync(sourceFile)) { process.exit(1); }
          if (!fs.existsSync(outputDir)) { fs.mkdirSync(outputDir); }
          const originalCode = fs.readFileSync(sourceFile, "utf8");

          const obfuscationOptions = {
              esModule: true,
              compact: true,
              controlFlowFlattening: true,
              deadCodeInjection: true,
              stringArray: true,
              // 注意：這裡不再需要 reservedNames，因為 userID 和 proxyIPs 不在此文件中
          };

          const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();
          fs.writeFileSync(outputFile, obfuscatedCode, "utf8");
          console.log(`Obfuscated logic saved to: ${outputFile}`);
          EOF
          node obfuscate-logic.js

          # --- 3. 合併文件 ---
          # 將乾淨的配置和混淆後的邏輯合併成最終的 opp.js 文件
          cat op.config.js dist/opp.logic.obfuscated.js > dist/opp.js
          echo "Final opp.js file created."

      - name: Commit and push the final file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add dist/opp.js
          
          if git diff --staged --quiet; then
            echo "No changes to commit, dist/opp.js is already up-to-date."
          else
            git commit -m "build: Split, obfuscate, and combine op.js"
            git push
          fi
