name: Obfuscate op.js with editable UUID and proxyIPs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install local JavaScript Obfuscator
      - name: Install JavaScript Obfuscator
        run: npm install javascript-obfuscator

      # 4. Generate and obfuscate op.js
      - name: Generate and obfuscate op.js
        run: |
          node <<'EOF'
          const fs = require('fs');
          const path = require('path');
          const crypto = require('crypto');
          const JavaScriptObfuscator = require('javascript-obfuscator');

          const sourceFile = 'op.js';
          const outputDir = 'dist';
          const outputFile = path.join(outputDir, 'opp.js');

          if (!fs.existsSync(sourceFile)) {
            console.error('Error: op.js not found');
            process.exit(1);
          }
          if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir);
          }

          const originalCode = fs.readFileSync(sourceFile, 'utf8');

          const obfuscationOptions = {
            esModule: true,
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 0.75,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 0.4,
            stringArray: true,
            stringArrayEncoding: ['base64'],
            stringArrayThreshold: 0.75,
            renameGlobals: true,
            identifierNamesGenerator: 'mangled',
            numbersToExpressions: true,
            splitStrings: true,
            splitStringsChunkLength: 10,
            transformObjectKeys: true,
            selfDefending: false,
            debugProtection: false
          };

          const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();

          // --- header 不混淆 ---
          const userID = process.env.USER_ID || crypto.randomUUID();
          const proxyIPsEnv = process.env.PROXY_IPS || '';
          const proxyArray = proxyIPsEnv.split(',').map(ip => ip.trim()).filter(ip => ip.length>0);
          // 保证即使为空也有双引号
          const header = `let userID = "${userID}";\nconst proxyIPs = [${proxyArray.length>0 ? proxyArray.map(ip => '"' + ip + '"').join(', ') : '""'}];`;

          fs.writeFileSync(outputFile, header + '\n\n' + obfuscatedCode, 'utf8');
          console.log(`Obfuscated file written to ${outputFile}, UUID: ${userID}`);
          EOF
        env:
          USER_ID: ${{ secrets.USER_ID || '' }}
          PROXY_IPS: ${{ secrets.PROXY_IPS || '' }}

      # 5. Commit & push dist/opp.js
      - name: Commit and push opp.js
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add dist/opp.js

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "build: Obfuscate op.js to dist/opp.js"
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
            git push origin "$BRANCH"
          fi

      # 6. Preview opp.js first 20 lines
      - name: Preview opp.js (first 20 lines)
        run: |
          echo "----- opp.js (first 20 lines) -----"
          head -n 20 dist/opp.js || true
          echo "-----------------------------------"
