name: Obfuscate op.js from Repository

on:
  workflow_dispatch:  # 允許手動觸發

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允許 workflow push 回倉庫

    steps:
      # 1. Checkout 倉庫
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 設定 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. 安裝混淆工具
      - name: Install JavaScript Obfuscator
        run: npm install javascript-obfuscator

      # 4. 產生並混淆 JS 檔案
      - name: Generate and obfuscate op.js
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const JavaScriptObfuscator = require('javascript-obfuscator');

          const sourceFile = 'op.js';
          const outputDir = 'dist';
          const outputFile = path.join(outputDir, 'opp.js');

          if (!fs.existsSync(sourceFile)) {
            console.error(\`Error: \${sourceFile} not found!\`);
            process.exit(1);
          }

          if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir);
          }

          const originalCode = fs.readFileSync(sourceFile, 'utf8');

          const obfuscationOptions = {
            esModule: true,
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 0.75,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 0.4,
            stringArray: true,
            stringArrayEncoding: ['base64'],
            stringArrayThreshold: 0.75,
            renameGlobals: true,
            identifierNamesGenerator: 'mangled',
            numbersToExpressions: true,
            splitStrings: true,
            splitStringsChunkLength: 10,
            transformObjectKeys: true,
            selfDefending: false,
            debugProtection: false
          };

          const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();

          // --- 已移除所有註解 ---
          const header = \`let userID = \"86c50e3a-5b87-49dd-bd20-03c7f2735e40\";\nconst proxyIPs = [\"\"];\`;

          const finalCode = header + '\n\n' + obfuscatedCode;

          fs.writeFileSync(outputFile, finalCode, 'utf8');
          console.log(\`Obfuscated file written to \${outputFile}\`);
          "

      # 5. Commit 並 push opp.js
      - name: Commit and push opp.js
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/opp.js
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "build: Obfuscate op.js to dist/opp.js"
            git push
          fi
