
name: Obfuscate op.js from blank

on:
  # 設置為手動觸發
  workflow_dispatch:
  # 當 op.js 文件有變更並推送到 main 分支時也會觸發
  push:
    branches:
      - main  # 或者您的默認分支名，如 master
    paths:
      - 'op.js'

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest

    # 授予 workflow 推送代碼的權限
    permissions:
      contents: write

    steps:
      # 1. 簽出您的倉庫代碼，這樣才能讀取到 op.js
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 設置 Node.js 環境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. 安裝混淆工具
      - name: Install JavaScript Obfuscator
        run: npm install javascript-obfuscator

      # 4. 生成並混淆為 opp.js (不修改 op.js 的版本)
      - name: Generate and obfuscate to opp.js
        run: |
          # 步驟 4.1: 創建一個 op.js 的臨時副本，並在末尾追加“使用”代碼
          TEMP_SOURCE_FILE="op-temp.js"
          cp op.js $TEMP_SOURCE_FILE
          # 追加一行無害的 IIFE (立即執行函數) 來引用變數，防止被當作無用代碼刪除
          # 這不會影響原始代碼的執行邏輯
          echo -e "\n;(()=>{return {userID, proxyIPs}})();" >> $TEMP_SOURCE_FILE

          # 步驟 4.2: 將混淆邏輯寫入一個臨時的 JS 腳本文件
          cat > obfuscate-temp.js <<'EOF'
          const fs = require("fs");
          const path = require("path");
          const JavaScriptObfuscator = require("javascript-obfuscator");

          // 修改這裡：讀取我們剛剛創建的臨時文件，而不是 op.js
          const sourceFile = "op-temp.js";
          
          const outputDir = "dist";
          const outputFile = path.join(outputDir, "opp.js");

          if (!fs.existsSync(sourceFile)) {
            console.error(`错误：臨時源文件 ${sourceFile} 未找到！`);
            process.exit(1);
          }
          
          if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir);
          }

          const originalCode = fs.readFileSync(sourceFile, "utf8");

          // --- 混淆配置 (保持不變) ---
          const obfuscationOptions = {
              esModule: true,
              renameGlobals: true,
              reservedNames: ['userID', 'proxyIPs'],
              compact: true,
              controlFlowFlattening: true,
              controlFlowFlatteningThreshold: 0.75,
              deadCodeInjection: true,
              deadCodeInjectionThreshold: 0.4,
              stringArray: true,
              stringArrayEncoding: ['base64'],
              stringArrayThreshold: 0.75,
              identifierNamesGenerator: 'mangled',
              numbersToExpressions: true,
              splitStrings: true,
              splitStringsChunkLength: 10,
              transformObjectKeys: true,
              selfDefending: false,
              debugProtection: false
          };

          console.log(`正在從 ${sourceFile} 讀取並混淆代碼...`);
          const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();
          console.log("代碼混淆完成。");

          fs.writeFileSync(outputFile, obfuscatedCode, "utf8");
          console.log(`混淆後的文件已保存到: ${outputFile}`);
          EOF

          # 步驟 4.3: 執行混淆腳本
          node obfuscate-temp.js

      # 5. 將生成的 dist/opp.js 文件提交並推送到倉庫
      - name: Commit and push the obfuscated file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add dist/opp.js
          
          if git diff --staged --quiet; then
            echo "No changes to commit, dist/opp.js is already up-to-date."
          else
            git commit -m "build: Obfuscate op.js to dist/opp.js"
            git push
          fi
