name: Obfuscate op.js fully

on:
  workflow_dispatch:

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install JavaScript Obfuscator
      - name: Install JavaScript Obfuscator
        run: npm install javascript-obfuscator

      # 4. Obfuscate op.js including UUID and proxyIPs
      - name: Obfuscate op.js
        run: |
          node <<'EOF'
          const fs = require('fs');
          const path = require('path');
          const JavaScriptObfuscator = require('javascript-obfuscator');

          const sourceFile = 'op.js';
          const outputDir = 'dist';
          const outputFile = path.join(outputDir, 'opp.js');

          if (!fs.existsSync(sourceFile)) {
            console.error('Error: op.js not found');
            process.exit(1);
          }
          if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir);
          }

          // 直接把 header 放在 op.js 前也混淆
          const userID = 'd78e37b0-09ff-46d0-890f-ff3791297005';
          const proxyIPs = [""];

          const header = `let userID = "${userID}";\nconst proxyIPs = ${JSON.stringify(proxyIPs)};\n\n`;

          const originalCode = fs.readFileSync(sourceFile, 'utf8');
          const combinedCode = header + originalCode;

          const obfuscationOptions = {
            esModule: true,
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 0.75,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 0.4,
            stringArray: true,
            stringArrayEncoding: ['base64'],
            stringArrayThreshold: 0.75,
            renameGlobals: true,
            identifierNamesGenerator: 'mangled',
            numbersToExpressions: true,
            splitStrings: true,
            splitStringsChunkLength: 10,
            transformObjectKeys: true,
            selfDefending: false,
            debugProtection: false
          };

          const obfuscatedCode = JavaScriptObfuscator.obfuscate(combinedCode, obfuscationOptions).getObfuscatedCode();
          fs.writeFileSync(outputFile, obfuscatedCode, 'utf8');
          console.log(`Obfuscated file written to ${outputFile}`);
          EOF

      # 5. Commit & push
      - name: Commit and push opp.js
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/opp.js
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "build: Fully obfuscate op.js to dist/opp.js"
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
            git push origin "$BRANCH"
          fi
