name: Generate and Obfuscate Worker Script

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Obfuscator
        run: npm install javascript-obfuscator

      - name: Create source file and obfuscate
        run: |
          node -e "
            const JavaScriptObfuscator = require('javascript-obfuscator');
            const fs = require('fs');

            const originalCode = process.env.SOURCE_CODE;
            if (!originalCode || originalCode.length < 50) {
              console.error('Error: Source code from secrets is missing or empty.');
              process.exit(1);
            }

            // --- 混淆配置 ---
            const obfuscationOptions = {
                compact: true,
                controlFlowFlattening: true,
                controlFlowFlatteningThreshold: 0.75,
                deadCodeInjection: true,
                deadCodeInjectionThreshold: 0.4,
                stringArray: true,
                stringArrayEncoding: ['base64'],
                stringArrayThreshold: 0.75,
                renameGlobals: true,
                identifierNamesGenerator: 'mangled',
                numbersToExpressions: true,
                splitStrings: true,
                splitStringsChunkLength: 10,
                transformObjectKeys: true,
                selfDefending: false,
                debugProtection: false,

                // 保留 userID 和 proxyIP 原始名称不混淆
                reservedNames: ['userID', 'proxyIP'],
            };

            const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();
            
            fs.writeFileSync('./opfsa', obfuscatedCode, 'utf8');
          "
        env:
          SOURCE_CODE: ${{ secrets.WORKER_SOURCE_CODE }}

      - name: Commit and push the obfuscated file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add opfsa
          if git diff --staged --quiet; then
            echo "No changes to commit, the obfuscated file is already up-to-date."
          else
            git commit -m "build: Generate and obfuscate worker script"
            git push
          fi
