name: Generate and Obfuscate Worker Script

on:
  workflow_dispatch:

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install JavaScript Obfuscator
        run: npm install javascript-obfuscator

      - name: Generate and backup opp.js
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const JavaScriptObfuscator = require('javascript-obfuscator');

          const sourceFile = path.resolve('op.js');
          if (!fs.existsSync(sourceFile)) {
            console.error('Error: op.js not found');
            process.exit(1);
          }

          const originalCode = fs.readFileSync(sourceFile, 'utf8');
          if (!originalCode || originalCode.length < 5) {
            console.error('Error: op.js is empty or too short');
            process.exit(1);
          }

          // 输出文件
          const outFile = path.resolve('opp.js');
          // 备份旧版本
          if (fs.existsSync(outFile)) {
            fs.copyFileSync(outFile, outFile + '.bak');
            console.log('Backed up existing opp.js to opp.js.bak');
          }

          const obfuscationOptions = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 0.75,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 0.4,
            stringArray: true,
            stringArrayEncoding: ['base64'],
            stringArrayThreshold: 0.75,
            renameGlobals: true,
            identifierNamesGenerator: 'mangled',
            numbersToExpressions: true,
            splitStrings: true,
            splitStringsChunkLength: 10,
            transformObjectKeys: true,
            selfDefending: false,
            debugProtection: false,
            disableConsoleOutput: true,
            reservedNames: ['^userID$', '^proxyIP$']
          };

          const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode(true);
          fs.writeFileSync(outFile, obfuscatedCode, 'utf8');
          console.log('OBFUSCATION_SUCCESS: wrote', outFile);
          "

      - name: Commit and push opp.js if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add opp.js
          # 如果有变化则 commit
          if git diff --cached --quiet; then
            echo "No changes in opp.js, skipping commit."
          else
            git commit -m "build: Update obfuscated opp.js"
            git push
          fi
