name: Generate and Obfuscate Worker Script

on:
  workflow_dispatch:

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2. 设置 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. 安装 javascript-obfuscator
      - name: Install JavaScript Obfuscator
        run: npm install javascript-obfuscator

      # 4. 混淆生成 opp.js，并备份旧版本
      - name: Generate and backup opp.js
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const JavaScriptObfuscator = require('javascript-obfuscator');

          const sourceFile = path.resolve('op.js');
          if (!fs.existsSync(sourceFile)) {
            console.error('Error: op.js not found');
            process.exit(1);
          }

          const originalCode = fs.readFileSync(sourceFile, 'utf8');
          if (!originalCode || originalCode.length < 5) {
            console.error('Error: op.js is empty or too short');
            process.exit(1);
          }

          const outFile = path.resolve('opp.js');
          if (fs.existsSync(outFile)) {
            fs.copyFileSync(outFile, outFile + '.bak');
            console.log('Backed up existing opp.js to opp.js.bak');
          }

          const obfuscationOptions = {
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 0.75,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 0.4,
            stringArray: true,
            stringArrayEncoding: ['base64'],
            stringArrayThreshold: 0.75,
            renameGlobals: true,
            identifierNamesGenerator: 'mangled',
            numbersToExpressions: true,
            splitStrings: true,
            splitStringsChunkLength: 10,
            transformObjectKeys: true,
            selfDefending: false,
            debugProtection: false,
            disableConsoleOutput: true,
            reservedNames: ['^userID$', '^proxyIP$']
          };

          const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode(true);
          fs.writeFileSync(outFile, obfuscatedCode, 'utf8');
          console.log('OBFUSCATION_SUCCESS: wrote', outFile);
          "

      # 5. 提交到新分支
      - name: Commit opp.js to new branch
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b build/opp-update
          git add opp.js
          git commit -m "build: Update obfuscated opp.js" || echo "No changes to commit"
          git push --set-upstream origin build/opp-update

      # 6. 自动创建 Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "build: Update obfuscated opp.js"
          branch: build/opp-update
          base: main
          title: "Update obfuscated opp.js"
          body: "This PR contains the latest obfuscated version of opp.js generated by GitHub Actions."
          labels: build, automated
